version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2015
configuration: Release
platform: x64
clone_depth: 50
install:
- cmd: >-
    mkdir build && cd build

    cmake .. -G "Visual Studio 14 2015 Win64"

    cd ..
build:
  project: build\ALL_BUILD.vcxproj
  verbosity: minimal
artifacts:
- path: bin/Release
  name: LearningDeepLearningFromScratch