version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
platform: x64
clone_depth: 50
before_build:
- ps: >-
    (New-Item build -type directory) -and (Set-Location build)

    cmake .. -G "Visual Studio 14 Win64"
build:
  project: C:\projects\learning-deep-learning-from-scratch\build\ALL_BUILD.vcxproj
  verbosity: minimal